using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MarketLine.Models
{
    public class SaleInvoice
    {
        public int Id { get; set; }

        public int? CustomerId { get; set; }
        public Customer? Customer { get; set; }

        // Snapshots of the customer details at the time of sale, so the
        // invoice stays accurate even if the customer's record is edited later.
        [StringLength(150)]
        public string CustomerName { get; set; } = string.Empty;

        [StringLength(250)]
        public string? CustomerAddress { get; set; }

        [StringLength(30)]
        public string? CustomerPhone { get; set; }

        public decimal TotalAmount { get; set; }

        // Relative web path to the saved receipt image (PNG), e.g.
        // "/uploads/receipts/abc123.png". Generated by the Preview page.
        public string? ReceiptImagePath { get; set; }

        public DateTime CreatedAt { get; set; } = DateTime.Now;

        public List<SaleInvoiceItem> Items { get; set; } = new();
    }

    public class SaleInvoiceItem
    {
        public int Id { get; set; }

        public int SaleInvoiceId { get; set; }
        public SaleInvoice? SaleInvoice { get; set; }

        // Null for manually typed items that don't match a catalog product
        public int? ProductId { get; set; }

        [Required]
        [StringLength(150)]
        public string Description { get; set; } = string.Empty;

        public decimal Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal TotalPrice { get; set; }
    }
}